# Generated by Django 4.2.16 on 2024-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='news',
            name='index',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.TextField(),
        ),
    ]
