# Generated by Django 4.2.16 on 2024-12-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_monthly_news_index_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='analysis',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
