services:
  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - secret.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django_web
   
    
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - secret.env

  celery:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery_worker
    command: ["celery", "-A", "mydjangoapp", "worker", "--loglevel=info"]
    
    depends_on:
      - redis
      - db
    env_file:
      - secret.env

  beat:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery_beat
    command: ["celery", "-A", "mydjangoapp", "beat", "--loglevel=info"]
  
    depends_on:
      - redis
      - db
    env_file:
      - secret.env 
    
  frontend:
    build: 
      context: .
      dockerfile: docker/next/Dockerfile
    container_name: frontend
    volumes:
       - ./frontend:/app  # Mount the local frontend directory to the container
       - /app/node_modules 
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - frontend
      - celery
      - beat
      - redis
      - db



volumes:
  postgres_data:
