services:
  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django_web
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery_worker
    command: ["celery", "-A", "mydjangoapp", "worker", "--loglevel=info"]
    
    depends_on:
      - redis
      - db
    env_file:
      - .env

  beat:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery_beat
    command: ["celery", "-A", "mydjangoapp", "beat", "--loglevel=info"]
  
    depends_on:
      - redis
      - db
    env_file:
      - .env 
    

volumes:
  postgres_data:
