
services:
  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - secret.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: django_web
    command: ["poetry","run","python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
       - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - secret.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery
    command: ["celery", "-A", "mydjangoapp", "worker", "--loglevel=info"]
    depends_on:
      - web
      - redis
      - db
    env_file:
      - secret.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  beat:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery_beat
    command: ["celery", "-A", "mydjangoapp", "beat", "--loglevel=info"]
    depends_on:
      - web
      - redis
      - db
    env_file:
      - secret.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/out:/usr/share/nginx/html 
    depends_on:
      - web
      - celery
      - beat
      - redis
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
