name: SSH and Run Script

on:
  push:
    branches:
      - main

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute script on remote server
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'bash -s' < ./sync.sh
          docker ps
          echo "Remote script executed"
